from datetime import timedelta

import google.auth
from google.auth.transport.requests import Request as GoogleAuthRequest
from google.cloud import storage
from google.cloud.exceptions import NotFound

from app.config import settings

_client: storage.Client | None = None
_signing_credentials = None


def _get_client() -> storage.Client:
    global _client
    if _client is None:
        _client = storage.Client()
    return _client


def _get_signing_kwargs() -> dict:
    """Credentials used locally lack a private key (they're just an access
    token), so signed URLs cannot be generated by signing locally. Instead
    we explicitly route signing through the IAM Credentials API (signBlob),
    which works the same way both locally (impersonating via our own
    gcloud identity) and on Cloud Run (via the service account's own
    identity) — as long as the signer has `roles/iam.serviceAccountTokenCreator`
    on itself."""
    global _signing_credentials
    if _signing_credentials is None:
        credentials, _ = google.auth.default()
        credentials.refresh(GoogleAuthRequest())
        _signing_credentials = credentials
    return {
        "service_account_email": settings.gcs_signer_service_account,
        "access_token": _signing_credentials.token,
    }


def get_blob_size(storage_path: str) -> int | None:
    bucket = _get_client().bucket(settings.gcs_bucket_name)
    blob = bucket.get_blob(storage_path)  # None if it doesn't exist
    return blob.size if blob is not None else None


def generate_upload_url(
    storage_path: str, content_type: str, expires_minutes: int
) -> str:
    bucket = _get_client().bucket(settings.gcs_bucket_name)
    blob = bucket.blob(storage_path)
    return blob.generate_signed_url(
        version="v4",
        expiration=timedelta(minutes=expires_minutes),
        method="PUT",
        content_type=content_type,
        **_get_signing_kwargs(),
    )


def generate_download_url(storage_path: str, expires_minutes: int) -> str:
    bucket = _get_client().bucket(settings.gcs_bucket_name)
    blob = bucket.blob(storage_path)
    return blob.generate_signed_url(
        version="v4",
        expiration=timedelta(minutes=expires_minutes),
        method="GET",
        **_get_signing_kwargs(),
    )


def delete_object(storage_path: str) -> None:
    bucket = _get_client().bucket(settings.gcs_bucket_name)
    blob = bucket.blob(storage_path)
    try:
        blob.delete()
    except NotFound:
        pass  # already gone — deleting is idempotent
