"""add priority in tasks table

Revision ID: e13e93d7f1f9
Revises: 72f29a7dd4fb
Create Date: 2026-09-19 16:33:04.242811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e13e93d7f1f9'
down_revision: Union[str, Sequence[str], None] = '72f29a7dd4fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.Integer(), nullable=False,server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
