"""change refresh tokens column revoked_at

Revision ID: f7fd3ca7bc48
Revises: e11a259c590e
Create Date: 2026-09-26 17:12:52.200753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7fd3ca7bc48'
down_revision: Union[str, Sequence[str], None] = 'e11a259c590e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('refresh_tokens', 'revoked_ad')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('revoked_ad', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('refresh_tokens', 'revoked_at')
    # ### end Alembic commands ###
